### ISSUE TITLE
Migrate to next 13 app directory with react server components

### ISSUE THREAD

**Issue by timlrx** [timlrx/pliny#80]
[Upgrade guide](https://beta.nextjs.org/docs/upgrade-guide#migrating-from-pages-to-app). 

Things to update:
- [x] Update starter blog template
- [ ] ~~Update CLI and Installer to reference `app` instead of `pages`~~
- [x] Update pliny components that might be using the older conventions e.g. SEO

Blockers:
- [next-themes appDir support](https://github.com/pacocoursey/next-themes/issues/152)
- [Contentlayer RSC support](https://github.com/contentlayerdev/contentlayer/issues/311)

**Comment by goatednews** [comment]
@timlrx  When we are planning to migrate it to Next 13?

**Comment by timlrx** [comment]
When next 13 is mature :) 

Since it is taking longer than I expected, I would probably migrate the current version using the `pages` directory first. I tried it out with the `app` directory but there would be quite a lot of breaking changes and if so I would prefer to approach it in one go when more of the tooling is available e.g. metadata support which could possibly render the SEO component redundant.

**Comment by capsloq** [comment]
I did upgrade a project based on this repo to nextjs13 without `App` directory. It was some time ago but pretty straight forward no major issues. Only thing i did not get to work is preact. I simply disabled it, since its not super important for my project. App directory is still not stable today, so no need to rush it.

Another thing which could be interesting for this project is [Contentlayer](https://github.com/contentlayerdev/contentlayer).
Didn't get to deep into it but its basically a typesafe mdx-bundler. Just gonna leaves this here from their docs:

> Libraries like [mdx-bundler](https://github.com/kentcdodds/mdx-bundler) and [next-mdx-remote](https://github.comhashicorp/next-mdx-remote) provide tooling to help in processing MDX.
> In addition to processing MDX, Contentlayer also parses and validates content and provides auto-generated TypeScript type definitions

**Comment by tothandras** [comment]
I'm pleased about your code @timlrx and would love to see you keep working on it. :) Can I help you with the migration? Are you planning to continue working on your project, or was it only a hobby project, should I reuse some of your code?

**Comment by timlrx** [comment]
I have decided to maintain most of the reusable components in this repository and deprecate the CLI and recipe features. All the components in the latest beta release have been updated to work with next 13 and app directory. The blog template is back in its original place and the [newest version in the V2 branch](https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/658) is a full Next 13 app directory setup.
