### ISSUE TITLE
A little bit of more customization out of the box

### ISSUE THREAD

**Issue by Jhoscy** [timlrx/pliny#85]
Hi!!
**Is your feature request related to a problem? Please describe.**
I was trying to understand how to customize a little bit the style of a pliny component but it's a little bit weird taking the reference from outside and make the style applied to it.

**Describe the solution you'd like**
I think is better to maintain the logic of the project out of the styling of a particular component (like NewsletterForm)

**Describe alternatives you've considered**
Maybe you can think an external props to pass in order to apply the style to the component (if it's tailwind event better becasue the template is built like this)

**Additional context**
I have all the style of the app refactored as "neuromorphism" and it's not too cool to see only the newsletter form out of this style.

If there are already solution about this feature pls let me know.

Tnx, great work.

**Comment by timlrx** [comment]
Thanks, I am a little on the fence on making some of the UI components more customizable, since I don't really plan on it being a "headless" UI component library, but I can understand that some level of customizability would be convenient. Most of the components are simple enough to just copy from the source code and modify to your liking. I just packaged them in the library to show how it would work with the other parts of the application.
